// <auto-generated />
namespace LinkInContactManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModifyToDoModel_Add_DateCompleted_And_Title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyToDoModel_Add_DateCompleted_And_Title));
        
        string IMigrationMetadata.Id
        {
            get { return "201701211701041_ModifyToDoModel_Add_DateCompleted_And_Title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
