// <auto-generated />
namespace LinkInContactManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddModel_ToDo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModel_ToDo));
        
        string IMigrationMetadata.Id
        {
            get { return "201701201930496_AddModel_ToDo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
